worker_processes auto;
events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # Явное определение MIME-типов
        types {
            text/css css;
            application/javascript js;
            text/html html;
        }

        # Настройки для статических файлов
        location ~* \.(js|css)$ {
            expires 30d;
            add_header Cache-Control "public";
        }
    }
}
